# interval, response_time_threshold, ssl_expired_before: can be s(second)/m(minutes)/h(hour)/d(day)/M(month)

monitor:
  - url: "http://example.com"
    enabled: true
    interval: 15s
    response_time_threshold: 5s
    ssl_monitoring: true
    ssl_expired_before: 4M